# Docker Compose v2 não precisa mais da versão

services:
  api-boleto:
    image: ghcr.io/diogenesmendes01/api-boletos-getway:latest
    container_name: api-boleto-olympia
    restart: always
    command: ["sh", "-c", "sleep 10 && npm run typeorm migration:run && node dist/src/main.js"]
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
      
      # ===== BANCO DE DADOS =====
      DB_HOST: postgres-olympia
      DB_PORT: "5432"
      DB_USERNAME: olympia_app
      DB_PASSWORD: V/aMMGypweFPSlGivTdcaC44zzEZDfuv
      DB_DATABASE: boleto_db
      
      # ===== REDIS =====
      REDIS_URL: redis://redis-boleto:6379
      
      # ===== SEGURANÇA =====
      JWT_SECRET: jwt_olympia_secret_change_this_2024
      JWT_EXPIRES_IN: 24h
      
      # ===== OLYMPIA BANK =====
      OLYMPIA_BASE_URL: https://api.olympiabank.net
      
      # ===== OUTROS =====
      API_BASE_URL: https://api.envio-boleto.olympiabank.xyz
      CORS_ORIGINS: https://envio-boleto.olympiabank.xyz
      LOG_LEVEL: info
      
    networks:
      - proxy-network
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    depends_on:
      redis-boleto:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # REDIS
  redis-boleto:
    image: redis:7-alpine
    container_name: redis-boleto
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - proxy-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:

networks:
  proxy-network:
    external: true