# docker-compose.prod.yml
version: '3.8'

services:
  api-boleto:
    image: ghcr.io/diogenesmendes01/api-boleto-gatway:latest
    container_name: api-boleto-olympia
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:postgres@postgres-olympia:5432/boleto_db
      - DB_HOST=postgres-olympia
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=boleto_db
      - REDIS_URL=redis://redis-boleto:6379
      - JWT_SECRET=${JWT_SECRET:-jwt_olympia_secret_change_this}
      - API_KEY=${API_KEY:-api_key_change_this}
      - CORS_ORIGINS=https://envio-boleto.olympiabank.xyz
      - LOG_LEVEL=info
    networks:
      - nginx-proxy-manager_default
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  nginx-proxy-manager_default:
    external: true